# Generated by Django 4.2.5 on 2023-11-17 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_product_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
