# Generated by Django 5.0.1 on 2024-04-06 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_product_reorder_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='reorder_level',
            new_name='reorderlevel',
        ),
    ]
