# Generated by Django 5.0.4 on 2024-05-02 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_purchaseorderstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.purchaseorderstatus'),
            preserve_default=False,
        ),
    ]
