# Generated by Django 5.0.4 on 2024-05-02 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_purchaseorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.ForeignKey(default='pending', on_delete=django.db.models.deletion.CASCADE, to='user.purchaseorderstatus'),
        ),
    ]
