# Generated by Django 5.0.4 on 2024-05-07 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_alter_purchaseorder_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='status',
        ),
    ]
