# Generated by Django 5.0.4 on 2024-05-15 18:27

import django.db.models.deletion
import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_purchaseorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.ForeignKey(default=user.models.get_default_status, on_delete=django.db.models.deletion.CASCADE, to='user.purchaseorderstatus'),
        ),
    ]
